### ISSUE TITLE
Ongelmia tests-haarassa

### ISSUE THREAD

**Issue by rpessi** [tihvis/latex-viitteet#5]
Testaus ei toimi muuten kuin että virheviestiä pukkaa. Luultavasti Library.py -tiedosto on pielessä, koska en ymmärrä miten sen olisi tarkoitus toimia. Näyttää myös siltä, ettei main.robot pääse käsiksi resource.robotin tietoihin, vaikka se on määritelty nähdäkseni oikein.

**Comment by tihvis** [comment]
Nämä fiksattu! SeleniumLibrary puuttui kehityksenaikaisista riippuvuuksista. Library.py on kunnossa, mutta localhostin osoite oli 5001 kun sen piti mystisesti olla 5000. Tiedä näistä :D
